name: Regression test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
 run:
  working-directory: ./ShoppingApp

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11 and Cache Gradle
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'gradle'

    - name: Grant execute permissions for gradlew
      run: chmod +x ./gradlew

    - name: Run UI tests
      uses: ReactiveCircus/android-emulator-runner@v2.30.1
      with:
        working-directory: ShoppingApp/
        api-level: 30
        arch: x86_64
        disable-animations: true
        emulator-options: -accel auto -no-snapshot-save -no-window -gpu auto -noaudio -no-boot-anim -camera-back none
        ram-size: 4096M
        script: |
          ./gradlew connectedAndroidTest
          adb pull /sdcard/Documents/allure-results
        
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: /sdcard/Documents/allure-results

    # - name: Publish test report
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: always()
    #   with:
    #      github_token: ${{ secrets.GITHUB_TOKEN }}
    #      publish_branch: gh-pages
    #      publish_dir: allure-history
