name: Regression test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
 run:
  working-directory: ./ShoppingApp

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11 and Cache Gradle
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'gradle'

    - name: Grant execute permissions for gradlew
      run: chmod +x ./gradlew

    - name: Run UI tests
      uses: ReactiveCircus/android-emulator-runner@v2.30.1
      if: always()
      with:
        working-directory: ShoppingApp/
        api-level: 30
        arch: x86_64
        disable-animations: true
        emulator-options: -accel auto -no-snapshot-save -no-window -gpu auto -noaudio -no-boot-anim -camera-back none
        ram-size: 4096M
        script: ./gradlew connectedAndroidTest

    - name: Upload jUnit report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui_tests_results
        path: ShoppingApp/app/build/reports/androidTests/connected

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always() 
      with:
         name: Test results          # Name of the check run which will be created
         path: ShoppingApp/app/build/outputs/androidTest-results/connected/*.xml    # Path to test results
         reporter: java-junit 
        
