name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Run UI tests
      uses: ReactiveCircus/android-emulator-runner@v2.30.1
      with:
          api-level: 33
          target: default
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=com.shopping.app.suites.Regression connectedAndroidTest
